### ISSUE TITLE
FATA[0000] json: cannot unmarshal bool into Go value of type int

### ISSUE THREAD

**Issue by dreamcat4** [ailispaw/talk2docker#12]
Not sure what's wrong here...

``` sh
id@emachines-e520:~$ talk2docker vs
FATA[0000] json: cannot unmarshal bool into Go value of type int 


id@emachines-e520:~$ talk2docker version --verbose
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
|               | VERSION | API VERSION | GO VERSION | GIT COMMIT |  OS   |  KERNEL VERSION   | ARCH  |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
| Talk2Docker   | 1.3.2   | 1.16        | go1.4.2    |            | linux |                   | amd64 |
| Docker Server | 1.7.1   | 1.19        | go1.4.2    | 786b29d    | linux | 3.19.0-23-generic | amd64 |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+


id@emachines-e520:~$ docker info
Containers: 26
Images: 359
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 411
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-23-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.792 GiB
Name: emachines-e520
ID: NG2B:QLY4:W2SH:6FQF:FYGU:TVLX:3IQL:CQ4S:N5DL:CTND:52ZD:GCDH


id@emachines-e520:~$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
id@emachines-e520:~$ 
```

**Comment by ailispaw** [comment]
Thank you for the report and using talk2docker still. :)
I have't used `vs` for a while.
It seems something has been changed in Docker v1.7.1.
I will check it out.

**Comment by ailispaw** [comment]
`/var/lib/docker/volumes/*/config.json` has been gone!!!

**Comment by ailispaw** [comment]
I have to parse all container's config.json instead now.
https://github.com/docker/docker/blob/master/daemon/volumes_unix.go

**Comment by ailispaw** [comment]
I will figure out how to handle volumes with new volume drivers properly.

**Comment by dreamcat4** [comment]
Great! Looking forward to it.

Thanks @ailispaw

**Comment by ailispaw** [comment]
Note: Fix stuff for docker 1.7
https://github.com/cpuguy83/docker-volumes/commit/2bd3dc0b2a04d1e2e470640eb31498b82d383923

**Comment by ailispaw** [comment]
Hmm
https://github.com/cpuguy83/docker-volumes/issues/18#issuecomment-130470510

**Comment by dreamcat4** [comment]
@ailispaw It seems he is referring to this ticket:

https://github.com/docker/docker/pull/8484#issuecomment-130452230

**Comment by ailispaw** [comment]
Oh!!
Add volume api by cpuguy83 · Pull Request #14242 · docker/docker
https://github.com/docker/docker/pull/14242

**Comment by ailispaw** [comment]
@dreamcat4 I'm sorry for this.
I'm going to drop `volume` command for now, until I find a good way to handle Docker volumes.
https://github.com/ailispaw/talk2docker/commit/c197e0466cd545b26657f555ba8d287d72c6aa54

It seems getting complicated with the new volume drivers.
I hope https://github.com/docker/docker/pull/14242 is good and released soon.

**Comment by dreamcat4** [comment]
Ok. Hopefully it will be possible to re-introduce the feature in a future docker version. Or at that time docker will provide it officially in the core program. Until then I'm already using an alternative method / technique to obtain my list of volumes folders. Which is something not as powerful / flexible but works sufficiently for my own needs (custom scripts leveraging yaml2json --> docker inspect --> jq).

**Comment by ailispaw** [comment]
Thank you for your understanding.

May I look at your custom script?
It would be very helpful and encouraging me before Docker releases the volume feature.

**Comment by ailispaw** [comment]
@dreamcat4 FYI, you might be interested in this.
Introducing Convoy a Docker Volume Driver for Backup and Recovery of Persistent Data | Rancher Labs
http://rancher.com/introducing-convoy-a-docker-volume-driver-for-backup-and-recovery-of-persistent-data/

**Comment by dreamcat4** [comment]
That new convoy looks great for my purpose. As backups is my whole use-case for finding the volumes on disk. I use duplicity tool. But it may be that I will switch over to convoy in future.

My script, it is not very easy to follow.

``` sh
# Backup docker config volumes
_backup_volume ()
{
# set -x
    local c="$1"; local v="$(sudo realpath "$2")"
    echo container:$c volume:$v

    _container_cfgvol_back="${_dkr_back}/volume/config/${c}"
    # mkdir -p "${_container_cfgvol_back}"
    mkdir -p "${_container_cfgvol_back}/dup"

    # Backup raw
    raw="${_container_cfgvol_back}/raw"
    sudo rm -rf "$raw"
    sudo cp -Rfp "$v" "$raw"
    sudo chmod -R g+rwx,o+rx "$raw"

    # Backup with duplicity
    duplicity --no-encryption "$raw" "file://${_container_cfgvol_back}/dup"
    # echo "$_sub_excludes" | duplicity --no-encryption --exclude-filelist-stdin  "$raw" "file://${_container_cfgvol_back}/dup"
    duplicity remove-all-but-n-full 1 --force "file://${_container_cfgvol_back}/dup"
# set +x
}

_dkr_back="${_dup_back}/var/lib/docker"
crane_json="$(cat "$crane_yml_file" | yaml2json)"
cc="$(echo "$crane_json" | jq -r '.containers|keys|.[]')"
containers=$(docker ps -aq)
for c in $containers; do
    res="$(docker inspect $c | jq -e -r -M '.[].Volumes["/config"]')" && rr="$rr
    $res"
done
volumes="$(echo "$rr" | sort | uniq | sed 1d)"
for v in $volumes; do
    for c in $ccf; do
        docker inspect $c | jq -e -r -M '.[].Volumes["/config"]' | grep -q "$v" && _backup_volume "$c" "$v" && break
    done
done
```

**Comment by ailispaw** [comment]
Thank you for your script.
`docker inspect` seems the only way to get volume information properly for now.

**Comment by ailispaw** [comment]
Merged!
https://github.com/docker/docker/pull/14242#event-393277449
