### ISSUE TITLE
Container run command

### ISSUE THREAD

**Issue by FabienMotte** [ailispaw/talk2docker#13]
First, thanks for this awesome Docker client !

But I can't figured out how to simply run a command in a new container with Talk2docker ? (like `docker run <image-name> <command>`)
I tried `talk2docker container run <image-name> <command>` intuitively but the command doesn't exist...
Is it normal, or maybe I missed something, or do you plan do add it ?

Thanks ! :smiley:

**Comment by ailispaw** [comment]
@FabienMotte Thank you for asking.

Unfortunately it doesn't have any interactive commands (run and exec), because I don't have enough experiences of Go lang yet.

But you can still use compose and start commands to run non-interactive (daemon) containers as below.

```
$ talk2docker compose <compose.yml>
$ talk2docker ctn start <container-name>
```
- Some categories and commands have their abbreviation. ex.) container: ctn, image: img

You can find some examples at https://github.com/ailispaw/talk2docker/tree/master/examples .
And also complex usages at https://github.com/ailispaw/consul-cluster .

Anyway I understand your points and I want the functionality, too.
I will consider it someday. Thanks. :smiley:

**Comment by FabienMotte** [comment]
Thank you for this quick answer !

Okay I understand, thanks for the links/examples, I will give a try.

Btw, the client is already great, for example, I wasn't able to set up Docker + Docker Machine with a CoreOS host, now with Talk2docker, I've only one executable and it works well with CoreOS, perfect !

Thanks again ! :smile:

**Comment by ailispaw** [comment]
Thank you so much for your comments!

I got just some ideas.
I may want `talk2docker host env` command to export environment variables for the original Docker cli,
and I may be able to create `talk2docker run` to run non-interactive containers for now.

**Comment by FabienMotte** [comment]
Oh definitively yes ! That would work and would be easier to do I suppose ?

I think you've just to export `DOCKER_HOST`, `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH` variables from the config file, and add an alias in Talk2docker for `docker run`command.

**Comment by ailispaw** [comment]
What do you mean the alias? Executes `docker run` in talk2docker? Sounds good and much easier. :)

**Comment by FabienMotte** [comment]
Yes, that's what I'm saying, sorry for the misunderstanding ! (:

**Comment by ailispaw** [comment]
That's a good idea! I will try it in the near future. Thank you so much!!

**Comment by ailispaw** [comment]
Add “host env” command
https://github.com/ailispaw/talk2docker/commit/f6971ec943dc4f69caa2ce3a8718177623d7078e

**Comment by ailispaw** [comment]
@FabienMotte 
Just released v1.6.0, which has `host env` and `docker` sub commands.
Now you can use any docker command through talk2docker with multiple host environments.

```
$ talk2docker docker run -- -it --rm busybox sh
/ #
```

Therefore, `host env` seems unnecessary any more. :p

**Comment by FabienMotte** [comment]
Just finish to test the new release, sooo nice from you ! "near future" as you said haha

Everything just works fine, so great to be able to use `talk2docker docker` or `docker` out of the box :smiley: 

Like you mention, the command `talk2docker host env`seems unless now, maybe you can plan to merge his behavior with the `talk2docker host switch <host>` command in the future release ?
When we switch to an another host, it would automatically sets the corresponding environment variables without the need to run also `talk2docker host env` command.

`talk2docker host env <host>` command would be useful only if we want to export the environment variables of a specific host. But well, to have this same behavior, just do `talk2docker host switch <host>`, it seems more logical from my point of view.

Hope you understood what I'm trying to say, what do you think about that ?

Also, thanks for the fix of `talk2docker host info <host>`command.

Thank you for your time and quick support !

**A quick note :** We need to pass like an extra empty argument (`--`) to every `talk2docker docker` command to make it work, like you did, right ?

**Comment by ailispaw** [comment]
Thank you for your idea again.
But I think it still needs `eval` to bring into effect and that won't work well with `host switch`.
So, I want to keep them.

```
$ eval $(talk2docker host env [host])
```

**Comment by FabienMotte** [comment]
It's okay, I forgot the `eval` part, better to keep them separate then :)

**Comment by ailispaw** [comment]
> A quick note : We need to pass like an extra empty argument (--) to every talk2docker docker command to make it work, like you did, right ?

Not every docker command, only if you want to pass options of docker cli but talk2docker to docker cli.

`--` means that it has talk2docker stop parsing arguments for talk2docker after that, therefore, you can pass any options, which talk2docker doesn't know, to docker cli.

`talk2docker docker run -it busybox sh` will cause a parse error, because talk2docker doesn't have -i and -t options.
`talk2docker docker version` is OK, because it doesn't have any options to parse.

**Comment by ailispaw** [comment]
Some other examples.

`talk2docker docker version -h` shows a usage of `talk2docker docker`.
In this case, `-h` is a help option of talk2docker.

`talk2docker docker version -- -h` shows a usage of `docker version`.
In this case, `-h` is passed to docker cli and it's a help option of docker cli.

**Comment by FabienMotte** [comment]
I get it now, thanks for these examples ! :)
