### ISSUE TITLE
volume list - FATA[0001] unexpected end of JSON input

### ISSUE THREAD

**Issue by dreamcat4** [ailispaw/talk2docker#8]
Hello,
I have compiled successfully `talk2docker` on `ubuntu-14.10` using the official go version `1.4.2`. However there is an error for the `volumes` subcommand.

``` sh
$ cat ~/.talk2docker/config 
default: default
hosts:
- name: default
  url: unix:///var/run/docker.sock

$ talk2docker volume list -V -D
FATA[0001] unexpected end of JSON input                 

$ echo $?
1

$ go version
go version go1.4.2 linux/amd64

$ talk2docker version
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
|               | VERSION | API VERSION | GO VERSION | GIT COMMIT |  OS   |  KERNEL VERSION   | ARCH  |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
| Talk2Docker   | 1.1.1   | 1.16        | go1.4.2    |            | linux |                   | amd64 |
| Docker Server | 1.5.0   | 1.17        | go1.4.1    | a8a31ef    | linux | 3.16.0-30-generic | amd64 |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
```

The same error occurs on `volumes inspect`. Even if the container name entered (for inspect subcmd) is invalid nonsense, and not a valid container.

Many other commands seems to work, including the following ones:

``` ti
talk2docker ls
talk2docker ps
talk2docker hosts
talk2docker version
talk2docker host info
talk2docker image search
```

**Comment by dreamcat4** [comment]
BTW, sorry I missed this information but

```
 Docker Server | 1.5.0   | 1.17 
```

It is Docker 1.5.0, which is the minimum version I can use now (for other reasons I can't revert back to older docker 1.4.1 anymore). And your tool was not tried on `docker 1.4.1` so unfortunately I can't discern if this error message is related to any possible `1.16` vs `1.17` API version changes.

BTW many thanks for adding volumes support into your tool (from the other `docker-volumes` tool). Appreciate it.

**Comment by ailispaw** [comment]
@dreamcat4 Thank you for letting me know this issue.
I will check it out.

**Comment by ailispaw** [comment]
@dreamcat4 One more thing. May I have an output of `talk2docker host info`?
I would like to know which storage driver it uses.

**Comment by ailispaw** [comment]
I use `vagrant` to build a ubuntu environment as below.

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "chef/ubuntu-14.10"

  config.vm.provision :shell do |sh|
    sh.privileged = false
    sh.inline = <<-EOT
      sudo apt-get update
      sudo apt-get install -y curl git

      # install Go
      curl -OL https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
      tar zxf go1.4.2.linux-amd64.tar.gz
      mkdir gosrc
      export GOPATH=$HOME/gosrc
      export GOROOT=$HOME/go
      export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

      # Install Godep
      go get github.com/tools/godep

      # Install Talk2Docker
      go get -d github.com/ailispaw/talk2docker
      cd $GOPATH/src/github.com/ailispaw/talk2docker && make install
      cd $HOME

      # install Docker
      curl -sSL https://get.docker.com/ubuntu/ | sudo sh

      # Set up envirroment variables
      echo export GOPATH=$HOME/gosrc >> .profile
      echo export GOROOT=$HOME/go >> .profile
      echo export PATH=$PATH:$GOPATH/bin:$GOROOT/bin >> .profile
      sudo adduser vagrant docker
    EOT
  end  
end
```

```
$ vagrant up
$ vagrant ssh
vagrant@vagrant:~$ talk2docker version
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
|               | VERSION | API VERSION | GO VERSION | GIT COMMIT |  OS   |  KERNEL VERSION   | ARCH  |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
| Docker Server | 1.5.0   | 1.17        | go1.4.1    | a8a31ef    | linux | 3.16.0-23-generic | amd64 |
| Talk2Docker   | 1.1.1   | 1.16        | go1.4.2    | 16ea87d    | linux |                   | amd64 |
+---------------+---------+-------------+------------+------------+-------+-------------------+-------+
vagrant@vagrant:~$ talk2docker ps
+----+-------+-------+---------+------------+--------+-------+
| ID | NAMES | IMAGE | COMMAND | CREATED AT | STATUS | PORTS |
+----+-------+-------+---------+------------+--------+-------+
+----+-------+-------+---------+------------+--------+-------+
vagrant@vagrant:~$ talk2docker volume list
+----+------------+------------+------+
| ID | MOUNTED ON | CREATED AT | PATH |
+----+------------+------------+------+
+----+------------+------------+------+
vagrant@vagrant:~$ talk2docker host info
+----------------------+-------------------------------------------------------------+
| Host                 | default                                                     |
| URL                  | unix:///var/run/docker.sock                                 |
| Description          |                                                             |
| TLS                  | No                                                          |
| Containers           | 0                                                           |
| Images               | 4                                                           |
| Storage Driver       | aufs                                                        |
| Root Dir             | /var/lib/docker/aufs                                        |
| Backing Filesystem   | extfs                                                       |
| Dirs                 | 4                                                           |
| Execution Driver     | native-0.2                                                  |
| Kernel Version       | 3.16.0-23-generic                                           |
| Operating System     | Ubuntu 14.10                                                |
| CPUs                 | 1                                                           |
| Total Memory         | 0.381 GB                                                    |
| Index Server Address | https://index.docker.io/v1/                                 |
| Memory Limit         | Supported                                                   |
| Swap Limit           | No                                                          |
| IPv4 Forwarding      | Enabled                                                     |
| ID                   | VUX5:6B4X:HW4P:63V7:FX7H:TBIC:HLQQ:YRKZ:CAAA:5C4Y:5EAT:RHP3 |
| Name                 | vagrant                                                     |
| Labels               |                                                             |
| Debug Mode           | No                                                          |
+----------------------+-------------------------------------------------------------+
```

It seems good.

**Comment by dreamcat4** [comment]
Thanks. And here is the missing `host info` output which was requested. Sorry for not providing that earlier on with the other stuff.

``` sh
$ talk2docker host info
+----------------------+-------------------------------------------------------------+
| Host                 | default                                                     |
| URL                  | unix:///var/run/docker.sock                                 |
| Description          |                                                             |
| TLS                  | No                                                          |
| Containers           | 262                                                         |
| Images               | 1229                                                        |
| Storage Driver       | aufs                                                        |
| Root Dir             | /var/lib/docker/aufs                                        |
| Backing Filesystem   | extfs                                                       |
| Dirs                 | 1753                                                        |
| Execution Driver     | native-0.2                                                  |
| Kernel Version       | 3.16.0-30-generic                                           |
| Operating System     | Ubuntu 14.10                                                |
| CPUs                 | 2                                                           |
| Total Memory         | 4.072 GB                                                    |
| Index Server Address | https://index.docker.io/v1/                                 |
| Memory Limit         | Supported                                                   |
| Swap Limit           | Supported                                                   |
| IPv4 Forwarding      | Enabled                                                     |
| ID                   | NG2B:QLY4:W2SH:6FQF:FYGU:TVLX:3IQL:CQ4S:N5DL:CTND:52ZD:GCDH |
| Name                 | emachines-e520                                              |
| Labels               |                                                             |
| Debug Mode           | No                                                          |
+----------------------+-------------------------------------------------------------+
```

**Comment by dreamcat4** [comment]
And for completeness, instructions to install the `docker-1.5.0` version, from docker's pre-release `testing` ubuntu apt repo. These commands:

``` sh
# docker - unstable
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 740B314AE3941731B942C66ADF4FD13717AAD7D6
sudo add-apt-repository -y "deb https://test.docker.com/ubuntu docker main"
sudo apt-get update -y
sudo apt-get install lxc-docker
```

**Comment by dreamcat4** [comment]
Oh wait… now I see that your vagrant box configuration has installed the same version of docker as mine, `1.5.0`. Last instruction were not necessary. And this newest docker version can / could work well enough.

Perhaps then it's more likely to be some other kind of issue. For example a data parsing or something. OR the input is too large, as I have many docker containers or volumes. Although that may not explain so well why also get the same error message when trying to inspect some individual non-existent volume.

Applying both the verbose and debug flags revealed no additional output to hint anything. So if you later decide to switch on some more / extra debugging in that area, would be very happy to try again, to gather a bit more data about this issue.

**Comment by ailispaw** [comment]
Oh so many containers!
I see. I will consider that extra debug messages.
Thanks.

**Comment by ailispaw** [comment]
@dreamcat4 
It may be something wrong with to get volume information from /var/lib/docker/volumes/*/config.json.
Could you provide an output of the following command on the host?

`awk '{cmd="ls -e " FILENAME; cmd | getline line; close(cmd); split(line,a," "); print $0,a[6],a[7],a[8],a[9],a[10]}' /var/lib/docker/volumes/*/config.json`

**Comment by ailispaw** [comment]
Possible cases;
1. I use `docker logs` to get the output of the command. The output may be too large.  
   I have to ignore the broken tail.
2. `"Path"` in the JSON string may have a space. It will cause the parse error.  
   This is my bug and I can fix it.

**Comment by ailispaw** [comment]
@dreamcat4 Anyway I fixed a bug at case 2. It had the same error message.
Please try it again with the latest master. https://github.com/ailispaw/talk2docker/commit/8120c28c14788fd0c4b4ee452b57745ef1a4c2cc

**Comment by dreamcat4** [comment]
@ailispaw OK i updated to master and recompiled on linux. It works now for me. No more errors with the volume list, or volume inspect commands.

Tried your query but `ls -e` isn't same on linux (GNU ls whatever has different switches). But hopefully you don't need to worry about that now. Thanks for fixing this.

Something else:

Was hoping to bring to your attention is an issue with the machine-readability of the output of your `volume list` command. You might not be interested in this. But my intention was to be passing the output to standard unix tools like sed, grep and cut etc. Without needing to resort to `json` or `yaml` etc. which are not quite so easy to deal with in a simple shell script or cron job.

Have recently explained my issue elsewhere, over on cpuguy's tool. Here is the details:

https://github.com/cpuguy83/docker-volumes/issues/20#issuecomment-75366025

Unfortunately, your tool is also using blank fields on repeating lines that have same volume. Meaning: whenever 1 volume is shared between multiple containers.

The command (that can't grepped) looks like this: 

``` sh
talk2docker volume list | cut -d'|' -f3,5
```

At the moment, my solution (for your tool) is to use `volume inspect` instead:

``` sh
talk2docker volume inspect my_container:/myvolume | grep -e '^ *path:' | cut -d ':' -f2
```

Anyway you may not be interested in any of that. If so then never mind about it. Please have a nice day. Thank you for the bug fix.

**Comment by ailispaw** [comment]
@dreamcat4 Thank you for your report. I will release it as v1.1.2.
How about the speed to list so many volumes?

As your suggestion, I would like to know the use case of that exactly, and I'm interested in that.
It might be an another option for the volume list command.
And also could you show me a sample output of volume list which you wanted?
It would be helpful for my understanding and consideration.

**Comment by ailispaw** [comment]
Could you open the separate issue for that?

**Comment by ailispaw** [comment]
```
$ talk2docker volume list --yaml | grep -e '^ *path:'
```

Does this work for you?

**Comment by ailispaw** [comment]
Oh you may need the pair of the path in a container and the path in a host, don't you?
Or just the host path?

**Comment by ailispaw** [comment]
```
docker_volume_to_backup="mycontainer:/volume"
directory_to_backup="$(talk2docker vol info $docker_volume_to_backup -Y | grep -e '^ *path:' | cut -d ' ' -f4)"
```

**Comment by ailispaw** [comment]
Oh You've already found the solution. Sorry that I didn't realize that.
Anyway I will wait for your reply.

**Comment by dreamcat4** [comment]
In respect to the initial question of volumes list speed for so many volumes: It is acceptable and similar processing time as cpuguy's tool is. Using `time` on my Core2Duo laptop (not a terribly fast computer), the time taken is 2.026 seconds. Which isn't bad in my opinion.

As for other use case indeed need _both_ container mounted path and real path fields. And it can be gotten around by calling the individual `inspect` cmd multiple times instead.

However when I use `time` on the inspect + grep + cut operation etc. It also take 2.005 seconds. Which is nearly the same time as listing all volumes in one go. The only benefit is to multi-line grep in one operation so I raise issue for that separately (and explain it's use case over there too). Many thanks.

**Comment by ailispaw** [comment]
@dreamcat4 
Thank you for the answer about speed. I'm glad to hear that it isn't bad.

All volume commands get all volume's information at first, so it causes slow execution even against just a single volume.

I understand the benefit of "multi-line grep in one operation" now. Thanks.
