### ISSUE TITLE
volume list: grep-able output on a single line

### ISSUE THREAD

**Issue by dreamcat4** [ailispaw/talk2docker#9]
Output needs to be parsable by standard unix tools such as `grep` `sed` and `cut`.

Current human readable output:

``` sh
| af7b6c9e612f | tvh_config:/config, tvheadend:/config,   | 2014-12-29 10:12:59 | /udf350/data/tvheadend/config                        |
|              | tvhconfig:/config                        |                     |                                                     
| e1adff28ee41 | tvh_config:/recordings                   | 2015-02-19 13:55:30 | /var/lib/docker/vfs/dir/<ID>                         |
```

Proposed machine-readable ouput (csv style):

``` sh
af7b6c9e612f<TAB>tvh_config:/config<TAB>2014-12-29 10:12:59<TAB>/udf350/data/tvheadend/config
af7b6c9e612f<TAB>tvheadend:/config<TAB>2014-12-29 10:12:59<TAB>/udf350/data/tvheadend/config
af7b6c9e612f<TAB>tvhconfig:/config<TAB>2014-12-29 10:12:59<TAB>/udf350/data/tvheadend/config
e1adff28ee41<TAB>tvh_config:/recordings<TAB>2015-02-19 13:55:30<TAB>/var/lib/docker/vfs/dir/????
```

There seem to be 2 things to be done.
- 1st issue is the real host path is missing on repeated lines.
- 2nd issue is that the directory string `/var/lib/docker/vfs/dir/<ID>` is never printed out the actual last path component `????`. It needs to be the full UUID path on the filesystem. Which actually is different to the UUID short form printed in the 1st column.

**Comment by dreamcat4** [comment]
It is not required to use `<TAB>` for the field separator - any character is fine that isn't occurring inside any of the fields. So you could stick with `|` or similar. That is fine. Sorry I forget myself which few characters are not permitted in unix filenames - they are good choices for the field separator.

**Comment by dreamcat4** [comment]
My intended usage. 2 Examples:

``` sh
# list of docker volumes to backup
volumes_to_backup="my_container_1:/myvolume1
my_container_2:/myvolume2
my_container_3:/myvolume3"

volumes_to_backup="$(docker volume list --machine-readable | grep --fixed-strings "$volumes_to_backup" | cut -d '|' -f2,4)"


# pass to duplicity (invoked from cron job) to backup each docker volume in the list
```

OR

``` sh
# select multiple docker volumes by regexp match ":myvolume*"
volumes_to_backup="$(docker volume list --machine-readable | grep -e ":myvolume*" | cut -d '|' -f2,4)"

# pass to duplicity (invoked from cron job) to backup each volume matched in the regexp
```

Where `duplicity` is a unix program for performing incremental backups.

**Comment by ailispaw** [comment]
@dreamcat4 Thank you for the explanations here and at another issue.
Let me try to make a prototype for that.

**Comment by ailispaw** [comment]
`--no-trunc` option seems good for this functionality of `volume list` as same as Docker's list commands.

**Comment by ailispaw** [comment]
@dreamcat4 Check out #10.

**Comment by dreamcat4** [comment]
Yes. Going by the sample output this new `--no-trunc` option looks pretty good to me. Thank you for adding that.

**Comment by ailispaw** [comment]
I released it as v1.2.0.

@dreamcat4 Thank you so much for your suggestion and making it better.
Please let me know any further ideas. I'd appreciate it. Thanks again.

**Comment by dreamcat4** [comment]
Great. Thanks for that. Since you have committed it to the master branch tonight I have just pulled and recompiled to `v1.2.0` with `go get ...`. The new `--no-trunc` switch works fine, just that it is not documented in the `help` usage information yet.

As a non-global flag you might find easiest to mention it here:

``` sh
# talk2docker help volume
Talk2Docker volume - Manage volumes

Usage: 
  talk2docker volume [command] [flags]
  talk2docker volume [command]

Aliases:
  volume, vol

Available Commands: 
-  list                                List volumes
+  list [--no-trunc]                   List volumes
etc...
```

Or else in the next help section entitled `Available Flags:`. Although maybe that part, which also documents the `--json` and `--yaml` switches is something that gets printed out globally for all subcommands. When `--no-trunc` may not be globally available.

Many thanks.

**Comment by ailispaw** [comment]
You can get full usage of each commands with the global option -h.

```
$ talk2docker volume list -h
Talk2Docker volume list - List volumes

Usage:
  talk2docker volume list [flags]

Aliases:
  list, ls

Flags:
  -a, --all=false: Show all volumes. Only active volumes are shown by default.
  -n, --no-header=false: Omit the header
      --no-trunc=false: Don't truncate output
  -q, --quiet=false: Only display numeric IDs

Global Flags:
  -C, --config="$HOME/.talk2docker/config": Path to the configuration file
  -D, --debug=false: Print debug messages
  -h, --help=false: help for list
  -H, --host="": Docker hostname to use its config (runtime only)
  -J, --json=false: Output in JSON format
  -V, --verbose=false: Print verbose messages
  -Y, --yaml=false: Output in YAML format

```
